// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJXNmdPcwwrx5CkLJQ9o1PB6Vys9vIrhs',
    appId: '1:843829285586:web:3bb2eb5e3717b3824b530b',
    messagingSenderId: '843829285586',
    projectId: 'pharma-scan-774b0',
    authDomain: 'pharma-scan-774b0.firebaseapp.com',
    storageBucket: 'pharma-scan-774b0.firebasestorage.app',
    measurementId: 'G-0GCHFLPS69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMQOd3wKCQN_kGUC3PvBDY8faasqhigw',
    appId: '1:843829285586:android:b712970a728d1f0e4b530b',
    messagingSenderId: '843829285586',
    projectId: 'pharma-scan-774b0',
    storageBucket: 'pharma-scan-774b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWDD2h-hwE5-dZkXrrkeHOQcjfZj7YLbI',
    appId: '1:843829285586:ios:921fa5c563662fe74b530b',
    messagingSenderId: '843829285586',
    projectId: 'pharma-scan-774b0',
    storageBucket: 'pharma-scan-774b0.firebasestorage.app',
    iosBundleId: 'com.example.pharmascan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWDD2h-hwE5-dZkXrrkeHOQcjfZj7YLbI',
    appId: '1:843829285586:ios:921fa5c563662fe74b530b',
    messagingSenderId: '843829285586',
    projectId: 'pharma-scan-774b0',
    storageBucket: 'pharma-scan-774b0.firebasestorage.app',
    iosBundleId: 'com.example.pharmascan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJXNmdPcwwrx5CkLJQ9o1PB6Vys9vIrhs',
    appId: '1:843829285586:web:8cff7ab5fe0d8b044b530b',
    messagingSenderId: '843829285586',
    projectId: 'pharma-scan-774b0',
    authDomain: 'pharma-scan-774b0.firebaseapp.com',
    storageBucket: 'pharma-scan-774b0.firebasestorage.app',
    measurementId: 'G-0GXEFJRM5T',
  );
}
